version: "3.8"

services:
  php:
    container_name: slim_php
    build:
      dockerfile: ./docker/php/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/slim_app
    command: sh -c "cd /var/www/slim_app && composer install && php-fpm"

  nginx:
    container_name: slim_nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/slim_app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: contraseñasecreta123
      MYSQL_USER: michael
      MYSQL_PASSWORD: contraseñamichael123
      MYSQL_DATABASE: PrestamosBiblioteca
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./setup-biblioteca-db.sql:/docker-entrypoint-initdb.d/setup-biblioteca-db.sql

volumes:
  mysql_data:
